name: haskoin-wallet
version: &version 0.8.3
synopsis: Lightweight command-line wallet for Bitcoin and Bitcoin Cash
description: !
  haskoin-wallet (hw) is a lightweight Bitcoin wallet using BIP39 mnemonics and

  BIP44 account structure. It requires a full blockchain index such as

  haskoin-store to query balances and unspent outputs. The wallet can both build

  transactions in read-only (xpub-only) mode and sign them in an offline

  environment.
category: Bitcoin, Finance, Network
author:
  - Philippe Laprade
  - Jean-Pierre Rupp
maintainer: jprupp@protonmail.ch
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin-wallet.git
homepage: http://github.com/haskoin/haskoin-wallet
bug-reports: http://github.com/haskoin/haskoin-wallet/issues
dependencies:
  base: ">=4.9 && <5"
  aeson: ">= 1.4.6.0"
  ansi-terminal: ">= 1.0"
  aeson-pretty: ">= 0.8.8"
  base16-bytestring: ">= 1.0.0.0"
  base64-bytestring: ">= 1.0.0.3"
  bytestring: ">= 0.10.10.0"
  cereal: ">= 0.5.8.1"
  conduit: ">= 1.3.5"
  containers: ">= 0.6.2.1"
  data-default: ">= 0.7.1.1"
  directory: ">= 1.3.6.0"
  Decimal: ">= 0.5.1"
  entropy: ">= 0.4.1.6"
  esqueleto: ">=3.5.10.1"
  haskeline: ">= 0.7.5.0"
  haskoin-core: ">= 1.0.4"
  haskoin-store-data: ">= 1.2.2"
  http-types: ">= 0.12.3"
  lens: ">= 4.18.1"
  lens-aeson: ">= 1.1"
  monad-logger: ">= 0.3.40"
  mtl: ">= 2.2.2"
  optparse-applicative: ">= 0.15.1.0"
  persistent: ">= 2.14.5.1"
  persistent-sqlite: ">= 2.13.1.1"
  pretty: ">= 1.1.3.6"
  random: ">= 1.1"
  raw-strings-qq: ">= 1.1"
  secp256k1-haskell: ">= 1.1.0"
  string-conversions: ">= 0.4.0.1"
  text: ">= 1.2.4.0"
  time: ">= 1.12.2"
  tostring: ">= 0.2.1.1"
  transformers: ">= 0.5.6.2"
  unordered-containers: ">= 0.2.10.0"
  wreq: ">= 0.5.3.2"
library:
  source-dirs: src
  ghc-options: -Wall
executables:
  hw:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
      haskoin-wallet: *version
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover
    ghc-options: -Wall
    dependencies:
      haskoin-wallet: *version
      hspec: ">= 2.7.1"
      QuickCheck: ">= 2.13.2"
      HUnit: ">= 1.6.0.0"
