resolver: nightly-2023-08-02
nix:
  packages:
  - zlib
  - secp256k1
  - pkg-config
extra-deps:
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 520b0b241f7e108771b0b0fd274a7c329f65ce1c
  - git: https://github.com/haskoin/haskoin-store.git
    commit: 5b87029c8cce9670fad421cfd271df75ca93739c
    subdirs:
    - data
