nix:
  packages:
    - zlib
    - secp256k1
    - pkg-config
resolver: lts-16.0
extra-deps:
- ../haskoin-core
- ../haskoin-store/data
- murmur3-1.0.4
- ansi-terminal-0.10.3
- parsec-extra-0.2.0.0
- secp256k1-haskell-0.2.4

